name: Deploy Vue App

on:
  push:
    branches: [ main ]
    paths: ["client/**", ".github/workflows/vue.yml"]
  pull_request:
    branches: [ main ]
    paths: ["client/**", ".github/workflows/vue.yml"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./client
    - run: npm run build
      working-directory: ./client
    - run: cp -r ./client/dist/. /var/www/hackathon.jparry.dev/html/
