name: Deploy Vue App

on:
  push:
    branches: [ main ]
    paths-ignore: ["server/**"]
  pull_request:
    branches: [ main ]
    paths-ignore: ["server/**"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run build
        cp -r dist/* /var/www/jacobparry.dev/html/
      working-directory: ./client
