# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Vue App

on:
  push:
    branches: [ main ]
    paths-ignore: ["server/**"]
  pull_request:
    branches: [ main ]
    paths-ignore: ["server/**"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd client
    - run: npm install
    - run: npm run build --if-present
    - run: cp -r dist/* /var/www/jacobparry.dev/html/
